# Opens a new UDP socket on the modem.

string  local_ip        # The IP address of the local endpoint.
uint16  local_port      # The port of the local endpoint.

---

bool    success         # Indicates if the socket was added.
uint32  server_id       # If successful, provides the ID of the opened socket.