# Opens a new UDP socket on the modem.

endpoint    local_endpoint      # The local endpoint to open the socket on.

---

bool        success         # Indicates if the socket was added.
uint32      socket_id       # If successful, provides the ID of the opened socket.